name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        name: [vim-v82-x64]
        include:
          - name: vim-v82-x64
            os: ubuntu-latest
            vim_version: 8.2.0037
            glibc_version: 2.15
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: rhysd/action-setup-vim@v1
        with:
          version: v8.2.0037
      - name: Download test runner
        shell: bash
        run: |
          git clone --depth 1 --single-branch https://github.com/junegunn/vader.vim.git ./tests/vader.vim
          git clone --depth 1 --single-branch https://github.com/Quramy/tsuquyomi.git ./tests/tsuquyomi

      - name: Run tests
        shell: bash
        run: |
          export PATH=~/vim/bin:$PATH
          cd ./tests
          yarn
          vim -u vimrc -c 'Vader! eslint.vader'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
